<?php
// Catálogo completo de productos — Ideas Empaque e Impresión
// imagenes: archivos en assets/img/productos/ (serie grande-XX-NN-MM.jpg)
// pdf: archivo en assets/pdf/

$PRODUCTOS = [

    // ─── BOLSAS DE POLIPROPILENO (CELOFÁN) ───────────────────────────────────
    'bolsas-de-sello-lateral' => [
        'nombre'      => 'Bolsas de sello lateral',
        'categoria'   => 'Bolsas de Polipropileno (Celofán)',
        'desc_corta'  => 'Generalmente se cierra con calor (selladora). Uso genérico: juguetes, frituras, productos de peso ligero, papelería.',
        'descripcion' => 'Bolsas de sello lateral (sin solapa). Generalmente se cierran con calor mediante una selladora. Son de uso genérico y resultan ideales para juguetes, frituras, productos de peso ligero y papelería. Fabricadas en polipropileno (celofán) de alta calidad.',
        'imagenes'    => ['grande-s-03-03.jpg', 'grande-s-03-01.jpg', 'grande-s-03-02.jpg'],
        'pdf'         => 'FICHA-s03.pdf',
        'cotizador'   => true,
    ],
    'bolsas-con-adhesivo-y-cenefa' => [
        'nombre'      => 'Bolsas con adhesivo y cenefa',
        'categoria'   => 'Bolsas de Polipropileno (Celofán)',
        'desc_corta'  => 'Bolsa con solapa adhesiva y cenefa. Sirve para exhibir productos en gancho o anaquel.',
        'descripcion' => 'Esta bolsa puede o no llevar solapa con adhesivo, y sirve para exhibir cualquier producto en un gancho o anaquel. Uso genérico: frituras, dulces, artículos escolares, accesorios para celular.',
        'imagenes'    => ['grande-s-04-03.jpg', 'grande-s-04-01.jpg', 'grande-s-04-02.jpg'],
        'pdf'         => 'FICHA-s04.pdf',
        'cotizador'   => false,
    ],
    'bolsas-de-sello-simplex' => [
        'nombre'      => 'Bolsas de sello simplex',
        'categoria'   => 'Bolsas de Polipropileno (Celofán)',
        'desc_corta'  => 'Bolsa de sello simplex en polipropileno. Ideal para empaque de productos pequeños.',
        'descripcion' => 'Bolsas de sello simplex fabricadas en polipropileno (celofán). Ideales para el empaque de productos pequeños, papelería y artículos de joyería. Se sellan con calor.',
        'imagenes'    => ['grande-s-05-03.jpg', 'grande-s-05-01.jpg', 'grande-s-05-02.jpg'],
        'pdf'         => 'FICHA-s05.pdf',
        'cotizador'   => false,
    ],
    'bolsas-de-sello-fondo' => [
        'nombre'      => 'Bolsas de sello fondo',
        'categoria'   => 'Bolsas de Polipropileno (Celofán)',
        'desc_corta'  => 'Bolsa con sello en el fondo. Excelente presentación para regalo y empaque de productos.',
        'descripcion' => 'Bolsas de sello fondo en polipropileno (celofán). Tienen sello en el fondo y apertura en la parte superior. Excelente presentación para regalos, alimentos, cosméticos y accesorios.',
        'imagenes'    => ['grande-s-06-03.jpg', 'grande-s-06-01.jpg', 'grande-s-06-02.jpg'],
        'pdf'         => 'FICHA-s06.pdf',
        'cotizador'   => false,
    ],

    // ─── SOBRES ──────────────────────────────────────────────────────────────
    'sobre-con-adhesivo' => [
        'nombre'      => 'Sobre con adhesivo',
        'categoria'   => 'Sobres',
        'desc_corta'  => 'Sobre con solapa adhesiva para cerrar fácilmente. Sin necesidad de selladora.',
        'descripcion' => 'Sobre de polipropileno con solapa adhesiva. Se cierra fácilmente sin necesidad de selladora. Ideal para papelería, documentos, fotografías y artículos pequeños.',
        'imagenes'    => ['grande-s-01-03.jpg', 'grande-s-01-01.jpg', 'grande-s-01-02.jpg'],
        'pdf'         => 'FICHA-s01.pdf',
        'cotizador'   => false,
    ],
    'sobre-sin-adhesivo' => [
        'nombre'      => 'Sobre sin adhesivo',
        'categoria'   => 'Sobres',
        'desc_corta'  => 'Sobre sin adhesivo. Se recomienda cerrar con sticker o selladora.',
        'descripcion' => 'Sobre de polipropileno sin adhesivo. Se recomienda cerrarlo con un sticker o mediante calor. Ideal para papelería, fotografías y productos que no requieren cierre permanente.',
        'imagenes'    => ['grande-s-02-01.jpg', 'grande-s-02-03.jpg'],
        'pdf'         => 'FICHA-s02.pdf',
        'cotizador'   => false,
    ],
    'sobre-con-adhesivo-y-cenefa' => [
        'nombre'      => 'Sobre con adhesivo y cenefa',
        'categoria'   => 'Sobres',
        'desc_corta'  => 'Sobre con adhesivo y cenefa decorativa. Para exhibición en gancho o anaquel.',
        'descripcion' => 'Sobre de polipropileno con solapa adhesiva y cenefa decorativa. Permite exhibir el contenido en ganchos o anaqueles. Uso genérico para artículos escolares, papelería y accesorios.',
        'imagenes'    => ['grande-s-04-03.jpg', 'grande-s-04-01.jpg'],
        'pdf'         => 'FICHA-s04.pdf',
        'cotizador'   => false,
    ],

    // ─── BOLSAS VARIADAS ─────────────────────────────────────────────────────
    'bolsas-de-polietileno' => [
        'nombre'      => 'Bolsas de polietileno',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas de polietileno de alta y baja densidad para múltiples usos industriales y comerciales.',
        'descripcion' => 'Bolsas de polietileno de alta y baja densidad. Disponibles en diferentes espesores y medidas. Ideales para uso industrial, comercial, empaque de alimentos y productos de consumo.',
        'imagenes'    => [],
        'pdf'         => '',
        'cotizador'   => false,
    ],
    'bolsas-de-polipapel' => [
        'nombre'      => 'Bolsas de polipapel',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Combinación de polietileno y papel. Resistentes y con excelente presentación.',
        'descripcion' => 'Bolsas de polipapel: combinación de polietileno y papel que ofrece resistencia y excelente presentación. Ideales para empaque de alimentos, productos gourmet y artículos de regalo.',
        'imagenes'    => ['grande-b-08-01-2.jpg', 'grande-b-08-03.jpg'],
        'pdf'         => 'FICHA-b08.pdf',
        'cotizador'   => false,
    ],
    'bolsa-con-cierre-ziplock' => [
        'nombre'      => 'Bolsas con cierre ziplock',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas resellables con cierre ziplock. Conservan frescura y protegen el contenido.',
        'descripcion' => 'Bolsas con cierre ziplock resellable. Conservan la frescura y protegen el contenido de polvo e humedad. Ideales para alimentos, tornillería, joyería, cosméticos y artículos pequeños.',
        'imagenes'    => ['grande-b-01-03.jpg', 'grande-b-01-01.jpg', 'grande-b-01-02.jpg'],
        'pdf'         => 'FICHA-b01.pdf',
        'cotizador'   => false,
    ],
    'bolsas-tipo-pouch' => [
        'nombre'      => 'Bolsas tipo Pouch',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas tipo Pouch con fuelle inferior. Se mantienen de pie y ofrecen excelente presentación en anaquel.',
        'descripcion' => 'Bolsas tipo Pouch con fuelle inferior que les permite mantenerse de pie. Ofrecen excelente presentación en anaquel. Ideales para alimentos, café, té, snacks y productos gourmet.',
        'imagenes'    => ['grande-b-02-03.jpg'],
        'pdf'         => 'FICHA-b02.pdf',
        'cotizador'   => false,
    ],
    'bolsas-tipo-canguro' => [
        'nombre'      => 'Bolsas tipo canguro',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas con asa troquelada tipo canguro. Prácticas para transporte y exhibición.',
        'descripcion' => 'Bolsas tipo canguro con asa troquelada para fácil transporte. Prácticas para distribución y exhibición de productos. Disponibles en diferentes materiales y medidas.',
        'imagenes'    => ['grande-b-03-03.jpg', 'grande-b-03-01.jpg', 'grande-b-03-02.jpg'],
        'pdf'         => 'FICHA-b03.pdf',
        'cotizador'   => false,
    ],
    'bolsas-de-papel-kraft' => [
        'nombre'      => 'Bolsas de papel kraft',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas de papel kraft ecológicas y resistentes. Perfectas para tiendas y regalos.',
        'descripcion' => 'Bolsas de papel kraft ecológicas y resistentes. Perfectas para tiendas de retail, panaderías, restaurantes y empaque de regalos. Con o sin asas.',
        'imagenes'    => ['grande-b-04-03.jpg', 'grande-b-04-01.jpg', 'grande-b-04-02.jpg'],
        'pdf'         => 'FICHA-b04.pdf',
        'cotizador'   => false,
    ],
    'bolsas-impresas' => [
        'nombre'      => 'Bolsas impresas',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas personalizadas con tu logo o diseño. Serigrafia y flexografía disponibles.',
        'descripcion' => 'Bolsas de polipropileno o polietileno con impresión personalizada. Contamos con serigrafía para pocas piezas y flexografía a 4, 6 y 8 colores para tirajes grandes. Imprime tu marca y diferénciate.',
        'imagenes'    => ['grande-b-05-03.jpg', 'grande-b-05-01.jpg'],
        'pdf'         => 'FICHA-b05.pdf',
        'cotizador'   => false,
    ],
    'bolsas-de-suaje-rinon' => [
        'nombre'      => 'Bolsas de suaje riñón',
        'categoria'   => 'Bolsas',
        'desc_corta'  => 'Bolsas con asa troquelada en forma de riñón. Muy resistentes y de excelente presentación.',
        'descripcion' => 'Bolsas con asa troquelada en forma de riñón. Muy resistentes y de excelente presentación. Ideales para tiendas de ropa, calzado, joyería y artículos de regalo.',
        'imagenes'    => ['grande-b-07-03.jpg', 'grande-b-07-01.jpg', 'grande-b-07-02.jpg'],
        'pdf'         => 'FICHA-b07.pdf',
        'cotizador'   => false,
    ],

    // ─── OTROS PRODUCTOS ─────────────────────────────────────────────────────
    'cintas-para-empaque' => [
        'nombre'      => 'Cintas para empaque',
        'categoria'   => 'Otros Productos',
        'desc_corta'  => 'Cintas adhesivas de polipropileno para empaque y embalaje. Alta resistencia.',
        'descripcion' => 'Cintas para empaque de polipropileno con adhesivo acrílico de alta resistencia. Disponibles en transparente, canela y diferentes anchos. Ideales para sellado de cajas y embalaje industrial.',
        'imagenes'    => ['grande-p-01-03.jpg', 'grande-p-01-01.jpg', 'grande-p-01-02.jpg'],
        'pdf'         => 'FICHA-p01.pdf',
        'cotizador'   => false,
    ],
    'cintas-doble-cara' => [
        'nombre'      => 'Cintas doble cara',
        'categoria'   => 'Otros Productos',
        'desc_corta'  => 'Cintas adhesivas con pegamento en ambas caras. Para montaje y fijación.',
        'descripcion' => 'Cintas de doble cara con adhesivo en ambas superficies. Ideales para montaje de materiales, fijación de alfombras, letreros y trabajos de carpintería y decoración.',
        'imagenes'    => ['grande-p-02-03.jpg', 'grande-p-02-01.jpg', 'grande-p-02-02.jpg'],
        'pdf'         => 'FICHA-p02.pdf',
        'cotizador'   => false,
    ],
    'rollos-de-poleolefina' => [
        'nombre'      => 'Rollos de poliolefina',
        'categoria'   => 'Otros Productos',
        'desc_corta'  => 'Película termoencogible de poliolefina para empaque con calor.',
        'descripcion' => 'Rollos de película termoencogible de poliolefina. Se utilizan con máquinas tuneladoras para el empaque con calor de productos. Excelente transparencia y resistencia al impacto.',
        'imagenes'    => ['grande-p-03-03.jpg', 'grande-p-03-01.jpg', 'grande-p-03-02.jpg'],
        'pdf'         => 'FICHA-p03.pdf',
        'cotizador'   => false,
    ],
    'pelicula-polistrech' => [
        'nombre'      => 'Película polystrech',
        'categoria'   => 'Otros Productos',
        'desc_corta'  => 'Película estirable para paletizado y sujeción de cargas en tarima.',
        'descripcion' => 'Película polystrech (estirable) para paletizado y sujeción de cargas en tarima. Alta resistencia al desgarro y elasticidad. Protege la carga durante transporte y almacenaje.',
        'imagenes'    => ['grande-p-04-03.jpg', 'grande-p-04-01.jpg', 'grande-p-04-02.jpg'],
        'pdf'         => 'FICHA-p04.pdf',
        'cotizador'   => false,
    ],
    'perchas-adhesivas' => [
        'nombre'      => 'Perchas adhesivas',
        'categoria'   => 'Otros Productos',
        'desc_corta'  => 'Perchas autoadhesivas para exhibición de productos en ganchos de anaquel.',
        'descripcion' => 'Perchas adhesivas para la exhibición de productos en ganchos de anaquel. Se adhieren directamente a la bolsa o empaque. Disponibles en diferentes tamaños y con o sin orificio de Euro.',
        'imagenes'    => ['grande-p-05-03.jpg', 'grande-p-05-01.jpg', 'grande-p-05-02.jpg'],
        'pdf'         => 'FICHA-p05.pdf',
        'cotizador'   => false,
    ],
    'tiras-exhibidoras' => [
        'nombre'      => 'Tiras exhibidoras',
        'categoria'   => 'Otros Productos',
        'desc_corta'  => 'Tiras plásticas para exhibición múltiple de productos en un solo gancho.',
        'descripcion' => 'Tiras exhibidoras de plástico para la exhibición de múltiples productos en un solo gancho de anaquel. Ideales para dulces, chicles, pilas, llaveros y artículos pequeños de papelería.',
        'imagenes'    => ['grande-p-06-03.jpg', 'grande-p-06-01.jpg', 'grande-p-06-02.jpg'],
        'pdf'         => 'FICHA-p06.pdf',
        'cotizador'   => false,
    ],
];

// Slugs que no son productos (para evitar 404 en producto.php)
$SLUGS_PAGINAS = ['quienes-somos', 'nosotros', 'productos', 'contacto', 'cotizador', 'gracias', 'inicio'];
